services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: ms-study-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: ms-study-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      zookeeper:
        condition: service_started

  mysql:
    image: mysql:8.4
    container_name: ms-study-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: study_ms
    ports:
      - '3307:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-proot']
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql

  users-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-study-users-service
    environment:
      PORT: 4001
      HOST: 0.0.0.0
      DATABASE_URL: mysql://root:root@mysql:3306/study_ms
      KAFKA_BROKER: kafka:9092
    command: sh -c "npm run prisma:generate && npm run db:push && npm run start:users"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - '4001:4001'

  orders-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-study-orders-service
    environment:
      PORT: 4002
      HOST: 0.0.0.0
      DATABASE_URL: mysql://root:root@mysql:3306/study_ms
      KAFKA_BROKER: kafka:9092
    command: sh -c "npm run prisma:generate && npm run start:orders"
    depends_on:
      mysql:
        condition: service_healthy
      users-service:
        condition: service_started
      kafka:
        condition: service_started
    ports:
      - '4002:4002'

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-study-auth-service
    environment:
      PORT: 4003
      HOST: 0.0.0.0
      DATABASE_URL: mysql://root:root@mysql:3306/study_ms
      KAFKA_BROKER: kafka:9092
    command: sh -c "npm run prisma:generate && npm run start:auth"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - '4003:4003'

  shipping-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-study-shipping-service
    environment:
      PORT: 4005
      HEALTH_PORT: 4015
      DATABASE_URL: mysql://root:root@mysql:3306/study_ms
      MELHOR_ENVIO_API_URL: https://sandbox.melhorenvio.com.br
      MELHOR_ENVIO_CLIENT_ID: '8829'
      MELHOR_ENVIO_CLIENT_SECRET: Wr1i1V1mBE0ql0dIuzxpt3jZK7tv1wNSP66iA4C6
      MELHOR_ENVIO_REDIRECT_URI: https://herbaceous-lullingly-earnest.ngrok-free.dev/shipping/auth/callback
      MELHOR_ENVIO_USER_AGENT: ag-ecommerce (suporte@ecommerce.com)
    command: sh -c "npm run prisma:generate && node dist/apps/shipping-service/main.js"
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '4005:4005'
      - '4015:4015'

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-study-api-gateway
    environment:
      NODE_ENV: production
      PORT: 3000
      FRONTEND_URL: http://localhost:3003
      USERS_SERVICE_HOST: users-service
      USERS_SERVICE_PORT: 4001
      ORDERS_SERVICE_HOST: orders-service
      ORDERS_SERVICE_PORT: 4002
      AUTH_SERVICE_HOST: auth-service
      AUTH_SERVICE_PORT: 4003
      PRODUCTS_SERVICE_HOST: product-service
      PRODUCTS_SERVICE_PORT: 4004
      SHIPPING_SERVICE_HOST: shipping-service
      SHIPPING_SERVICE_PORT: 4005
    command: sh -c "npm run prisma:generate && node dist/apps/api-gateway/main.js"
    depends_on:
      users-service:
        condition: service_started
      orders-service:
        condition: service_started
      auth-service:
        condition: service_started
      shipping-service:
        condition: service_started
    ports:
      - '3010:3000'

volumes:
  mysql_data:
