export const ORDERS_REPOSITORY = Symbol('ORDERS_REPOSITORY');
export const KNOWN_USERS_REPOSITORY = Symbol('KNOWN_USERS_REPOSITORY');
export const ORDERS_EVENTS_PUBLISHER = Symbol('ORDERS_EVENTS_PUBLISHER');
