export const PRODUCTS_REPOSITORY = Symbol('PRODUCTS_REPOSITORY');
export const CATEGORIES_REPOSITORY = Symbol('CATEGORIES_REPOSITORY');
export const PRODUCTS_EVENTS_PUBLISHER = Symbol('PRODUCTS_EVENTS_PUBLISHER');
