export const PAYMENTS_REPOSITORY = Symbol('PAYMENTS_REPOSITORY');
export const PAYMENT_GATEWAY_REGISTRY = Symbol('PAYMENT_GATEWAY_REGISTRY');
export const PAYMENTS_EVENTS_PUBLISHER = Symbol('PAYMENTS_EVENTS_PUBLISHER');
